-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 20:11:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `SSN` VARCHAR(14) NOT NULL,
  `Emp_Gender` VARCHAR(6) NOT NULL,
  `Emp_Bdata` DATE NOT NULL,
  `F_name` VARCHAR(30) NOT NULL,
  `M_name` VARCHAR(30) NOT NULL,
  `L_name` VARCHAR(30) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Zip_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`SSN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JOB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JOB` (
  `id` INT NOT NULL,
  `Job_Type` VARCHAR(12) NOT NULL,
  `Emp_ssn` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`, `Emp_ssn`),
  INDEX `fk_JOB_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_JOB_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal Owner` (
  `SSN` VARCHAR(14) NOT NULL,
  `Own_Gender` VARCHAR(6) NOT NULL,
  `Emp_ssn` VARCHAR(14) NOT NULL,
  `F_name` VARCHAR(30) NOT NULL,
  `M_name` VARCHAR(30) NOT NULL,
  `L_name` VARCHAR(30) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Zip_Code` VARCHAR(10) NULL,
  PRIMARY KEY (`SSN`),
  INDEX `fk_Animalowner_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Animalowner_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factions` (
  `id` INT NOT NULL,
  `Fact_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet` (
  `id` INT NOT NULL,
  `Own_ssn` VARCHAR(14) NOT NULL,
  `Fact_id` INT NOT NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pet_Animalowner_idx` (`Own_ssn` ASC) VISIBLE,
  INDEX `fk_Pet_Factions_idx` (`Fact_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pet_Animalowner`
    FOREIGN KEY (`Own_ssn`)
    REFERENCES `mydb`.`Animal Owner` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pet_Factions`
    FOREIGN KEY (`Fact_id`)
    REFERENCES `mydb`.`Factions` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination` (
  `id` INT NOT NULL,
  `Vacc_Type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emp_Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emp_Pet` (
  `Emp_ssn` VARCHAR(14) NOT NULL,
  `Pet_id` INT NOT NULL,
  PRIMARY KEY (`Emp_ssn`, `Pet_id`),
  INDEX `fk_Emppet_Pet_idx` (`Pet_id` ASC) VISIBLE,
  INDEX `fk_Emppet_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Emppet_Pet`
    FOREIGN KEY (`Pet_id`)
    REFERENCES `mydb`.`Pet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Emppet_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_Vacc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_Vacc` (
  `Pet_id` INT NOT NULL,
  `Vacc_id` INT NOT NULL,
  PRIMARY KEY (`Pet_id`, `Vacc_id`),
  INDEX `fk_Petvacc_Vaccination_idx` (`Vacc_id` ASC) VISIBLE,
  INDEX `fk_Petvacc_Pet_idx` (`Pet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Petvacc_Pet`
    FOREIGN KEY (`Pet_id`)
    REFERENCES `mydb`.`Pet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Petvacc_Vaccination`
    FOREIGN KEY (`Vacc_id`)
    REFERENCES `mydb`.`Vaccination` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emp_Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emp_Phone` (
  `Emp_ssn` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Emp_ssn`, `phone`),
  INDEX `fk_Empphone_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Empphone_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificate` (
  `Cert_id` VARCHAR(60) NOT NULL,
  `Certificate` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Cert_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emp_Cert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emp_Cert` (
  `Emp_ssn` VARCHAR(14) NOT NULL,
  `Cert_id` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Emp_ssn`, `Cert_id`),
  INDEX `fk_Empcert_Certificate_idx` (`Cert_id` ASC) VISIBLE,
  INDEX `fk_Empcert_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Empcert_Certificate`
    FOREIGN KEY (`Cert_id`)
    REFERENCES `mydb`.`Certificate` (`Cert_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empcert_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Own_Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Own_Phone` (
  `Own_ssn` VARCHAR(14) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Own_ssn`, `phone`),
  INDEX `fk_Ownphone_Animalowner_idx` (`Own_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Ownphone_Animalowner`
    FOREIGN KEY (`Own_ssn`)
    REFERENCES `mydb`.`Animal Owner` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emp_salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emp_salary` (
  `Emp_ssn` VARCHAR(14) NOT NULL,
  `Emp_salary` DOUBLE NULL,
  `Emp_Bouns` DOUBLE NULL,
  `Emp_Penalties` DOUBLE NULL,
  `Net_salary` DOUBLE NOT NULL,
  PRIMARY KEY (`Emp_ssn`, `Net_salary`),
  INDEX `fk_Empsalary_Employee_idx` (`Emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Empsalary_Employee`
    FOREIGN KEY (`Emp_ssn`)
    REFERENCES `mydb`.`Employee` (`SSN`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Behavior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Behavior` (
  `Id_bev` INT NOT NULL,
  `Behavior` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_bev`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_behavior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_behavior` (
  `Pet_id` INT NOT NULL,
  `Id_bev` INT NOT NULL,
  PRIMARY KEY (`Pet_id`, `Id_bev`),
  INDEX `fk_Petbehavior_Behavior_idx` (`Id_bev` ASC) VISIBLE,
  INDEX `fk_Petbehavior_Pet_idx` (`Pet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Petbehavior_Behavior`
    FOREIGN KEY (`Id_bev`)
    REFERENCES `mydb`.`Behavior` (`Id_bev`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Petbehavior_Pet`
    FOREIGN KEY (`Pet_id`)
    REFERENCES `mydb`.`Pet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Previous Diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Previous Diseases` (
  `Id_pre_dis` INT NOT NULL,
  `Pre_diseases` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_pre_dis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pet_Pre_Diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pet_Pre_Diseases` (
  `Pet_id` INT NOT NULL,
  `Id_pre_dis` INT NOT NULL,
  PRIMARY KEY (`Pet_id`, `Id_pre_dis`),
  INDEX `fk_Petprediseases_Pet_idx` (`Pet_id` ASC) VISIBLE,
  INDEX `fk_Petprediseases_PreviousDiseases_idx` (`Id_pre_dis` ASC) VISIBLE,
  CONSTRAINT `fk_Petprediseases_PreviousDiseases`
    FOREIGN KEY (`Id_pre_dis`)
    REFERENCES `mydb`.`Previous Diseases` (`Id_pre_dis`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Petprediseases_Pet`
    FOREIGN KEY (`Pet_id`)
    REFERENCES `mydb`.`Pet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
